# Generated by Django 5.1 on 2026-05-03 23:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель'), ('admin', 'Администратор'), ('head', 'Руководитель'), ('methodist', 'Методист')], max_length=20, verbose_name='Роль в системе')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ControlForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Форма контроля')),
            ],
            options={
                'verbose_name': 'Форма итогового контроля',
                'verbose_name_plural': 'Формы итогового контроля',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_open', models.BooleanField(default=True, verbose_name='Статус (открыто)')),
            ],
            options={
                'verbose_name': 'Направление обучения',
                'verbose_name_plural': 'Направления обучения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название группы')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('distance', 'Дистанционная')], max_length=20, verbose_name='Форма обучения')),
                ('date_start', models.DateField(verbose_name='Дата начала обучения')),
                ('date_finish', models.DateField(verbose_name='Дата окончания обучения')),
                ('status', models.CharField(choices=[('forming', 'Формируется'), ('studying', 'Обучается'), ('graduated', 'Выпущена')], default='forming', max_length=20, verbose_name='Статус')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='unicron_app.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('hours', models.PositiveIntegerField(verbose_name='Количество часов')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('control_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicron_app.controlform', verbose_name='Форма итогового контроля')),
                ('directions', models.ManyToManyField(related_name='subjects', to='unicron_app.direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время завершения')),
                ('format', models.CharField(choices=[('offline', 'Очно'), ('online', 'Дистанционно')], max_length=10, verbose_name='Формат обучения')),
                ('classroom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Аудитория')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видеоконференцию')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('change_reason', models.TextField(blank=True, verbose_name='Причина изменения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedules', to='unicron_app.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicron_app.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['date', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('studying', 'Обучается'), ('dismissed', 'Отчислен'), ('graduated', 'Выпущен')], default='studying', max_length=20, verbose_name='Статус обучения')),
                ('date_enrolled', models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicron_app.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(choices=[('current', 'Текущий'), ('intermediate', 'Промежуточный'), ('final', 'Итоговый')], max_length=20, verbose_name='Тип контроля')),
                ('date', models.DateField(verbose_name='Дата выставления')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Балл')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='Зачёт/незачёт')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicron_app.group', verbose_name='Группа')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicron_app.schedule', verbose_name='Связанное занятие')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicron_app.subject', verbose_name='Предмет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicron_app.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('max_weekly_hours', models.PositiveIntegerField(default=36, verbose_name='Максимальная нагрузка (часов в неделю)')),
                ('hire_date', models.DateField(verbose_name='Дата приёма на работу')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('fired', 'Уволен')], default='studying', max_length=20, verbose_name='Статус')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicron_app.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicron_app.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('is_present', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicron_app.group', verbose_name='Группа')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='unicron_app.schedule', verbose_name='Занятие')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicron_app.subject', verbose_name='Предмет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicron_app.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'unique_together': {('schedule', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='unicron_app.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='unicron_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_entries', to='unicron_app.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'unique_together': {('group', 'subject')},
            },
        ),
    ]
