# Generated by Django 5.1 on 2026-05-09 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicron_app', '0002_alter_schedule_options_rename_study_form_group_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secretary_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='secretary_photos/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Секретарь',
                'verbose_name_plural': 'Секретари',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель'), ('admin', 'Администратор'), ('head', 'Руководитель'), ('methodist', 'Методист'), ('secretary', 'Секретарь приёмной комиссии')], max_length=20, verbose_name='Роль'),
        ),
    ]
