# Generated by Django 5.1 on 2026-05-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicron_app', '0003_secretary_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Номер аудитории')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('capacity', models.PositiveSmallIntegerField(default=20, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicron_app.room', verbose_name='Аудитория'),
        ),
    ]
